version: "3"
services:
  rabbitmq:    
      build:
        context: .
        dockerfile: rabbit-mq-plugins.dockerfile
      ports:
      - "15672:15672"  #Management
      - "5672:5672"    #AMQP
      - "25672:25672"  #clustering
      
      - "1883:1883"    #mqtt
      - "15675:15675"  #http/web-mqtt

      - "61613:61613"  #stomp
      - "15674:15674"  #http/web-stomp
      environment:
        RABBITMQ_DEFAULT_USER: usuario
        RABBITMQ_DEFAULT_PASS: senha
        RABBITMQ_DEFAULT_VHOST: vhost
      volumes:
        - mq_data:/var/lib/rabbitmq/mnesia
  gen-sonar:
    image: sonarqube:8.2-community
    container_name: sonar
    ports:
      - 9001:9000
      - 9092:9092
  redis:
    container_name: journal_redis
    image: redis
    command: redis-server --requirepass local --protected-mode no
    hostname: redis
    ports:
      - 6379:6379
  postgres:
    container_name: journal_database
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=journal_vtex
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/journal_vtex
    restart: always
    command: bash -c "npm install --only=production && npm run debug"
    volumes:
      - ./dist/:/usr/src/journal_vtex/dist/
      - ./package.json:/usr/src/journal_vtex/package.json
    ports:
      - "5051:5051"
      - "9222:9222"
volumes:
  mq_data: