version: "4"
services:
  redis:
    container_name: journal_redis
    image: redis
    command: redis-server --requirepass local --protected-mode no
    hostname: redis
    ports:
      - 6379:6379
  postgres:
    container_name: journal_database
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=journal_vtex
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/journal_vtex
    restart: always
    command: bash -c "npm install --only=production && npm run debug"
    volumes:
      - ./dist/:/usr/src/journal_vtex/dist/
      - ./package.json:/usr/src/journal_vtex/package.json
    ports:
      - "5051:5051"
      - "9222:9222"
    links:
      - redis,postgres